version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - ./src:/var/www/laravel
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  composer:
    build:
      context: docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel